[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Andres de Lago <delagoandres@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
itertools = "0.9"
aoc-next = "0.1"
regex = "1.4"
lazy_static = "1.4"
